export { StrX } from './src/StrX'
export { ArrX } from './src/ArrX'
export { MatX } from './src/MatX'
export { MapX } from './src/MapX'
export { EntX } from './src/EntX'
export { TableX } from './src/TableX'
export { CrosTabX } from './src/CrosTabX'
export { deco, deca, decoLog } from '@spare/deco'
export { logger, logNeL } from '@spare/logger'
export { Xr, xr } from '@spare/xr'
export { totx, noop } from '@spare/util'
export { Preci } from '@spare/preci'
export { ClicheFin as FinFm } from '@cliche/fin'
export { ClicheMag as MagFm } from '@cliche/mag'
export { ClicheRatio as RatioFm } from '@cliche/ratio'
export { toPercent } from '@cliche/to-percent'
